/*
| A user.
*/


/*
| Capsule
*/
( function( ) {
"use strict";


/*
| The jion definition.
*/
if( JION )
{
	return {
		id :
			'server_user',
		attributes :
			{
				username :
					{
						comment :
							'the username',
						type :
							'string',
					},
				pass :
					{
						comment :
							'password hash',
						type :
							'string'
					},
				mail :
					{
						comment :
							'the users email',
						type :
							'string',
						defaultValue :
							'""'
					},
				news :
					{
						comment :
							'if the user checked okay with news emails',
						type :
							[ 'boolean', 'string' ],
					},
				clearPass :
					{
						comment :
							'clear password for autogenerated users',
						type :
							'string',
						allowsUndefined :
							true
					}
			}
	};
}


require( '../jion/this' )( module );


}( ) );
