#!/bin/bash
set -e
rm -f jion/server/* jion/shell/*
node --harmony src/tools/genjion.js --all jion/listing-genjion.js
node --harmony src/tools/genjion.js jion/listing-server.js
node --harmony src/server/server.js
