module.exports =
{
	app :
		'server',
	list :
		[
			'src/euclid/margin.js',
			'src/euclid/point.js',
			'src/euclid/rect.js',
			'src/euclid/view.js',
			'src/jion/path.js',
			'src/ccot/change.js',
			'src/ccot/change-ray.js',
			// FUTURE check server really using
			// these two
			'src/ccot/change-wrap.js',
			'src/ccot/change-wrap-ray.js',
			'src/ccot/sign.js',
			'src/ccot/sign-ray.js',
			'src/result/genjion.js',
			'src/server/resource.js',
			'src/server/inventory.js',
			'src/visual/doc.js',
			'src/visual/label.js',
			'src/visual/note.js',
			'src/visual/para.js',
			'src/visual/portal.js',
			'src/visual/relation.js',
			'src/visual/space.js',

			// built-in genjion
			'src/ast/ast-and.js',
			'src/ast/ast-array-literal.js',
			'src/ast/ast-assign.js',
			'src/ast/ast-block.js',
			'src/ast/ast-boolean.js',
			'src/ast/ast-call.js',
			'src/ast/ast-case.js',
			'src/ast/ast-check.js',
			'src/ast/ast-comma-list.js',
			'src/ast/ast-comment.js',
			'src/ast/ast-condition.js',
			'src/ast/ast-delete.js',
			'src/ast/ast-differs.js',
			'src/ast/ast-dot.js',
			'src/ast/ast-equals.js',
			'src/ast/ast-fail.js',
			'src/ast/ast-file.js',
			'src/ast/ast-for.js',
			'src/ast/ast-for-in.js',
			'src/ast/ast-func.js',
			'src/ast/ast-func-arg.js',
			'src/ast/ast-greater-than.js',
			'src/ast/ast-if.js',
			'src/ast/ast-instanceof.js',
			'src/ast/ast-less-than.js',
			'src/ast/ast-member.js',
			'src/ast/ast-new.js',
			'src/ast/ast-not.js',
			'src/ast/ast-null.js',
			'src/ast/ast-number.js',
			'src/ast/ast-obj-literal.js',
			'src/ast/ast-or.js',
			'src/ast/ast-plus.js',
			'src/ast/ast-plus-assign.js',
			'src/ast/ast-pre-increment.js',
			'src/ast/ast-return.js',
			'src/ast/ast-string.js',
			'src/ast/ast-switch.js',
			'src/ast/ast-typeof.js',
			'src/ast/ast-var.js',
			'src/ast/ast-var-dec.js',
			'src/ast/ast-vlist.js',

			'src/format/context.js',
			'src/jion/gen.js'
		]
};
