module.exports =
{
	app :
		'genjion',
	force :
		true,
	list :
		[
			'src/code/a-null.js',
			'src/code/an-and.js',
			'src/code/an-array-literal.js',
			'src/code/an-assign.js',
			'src/code/a-block.js',
			'src/code/a-boolean-literal.js',
			'src/code/a-call.js',
			'src/code/a-case.js',
			'src/code/a-check.js',

			'src/code/comma-list.js',
			'src/code/comment.js',
			'src/code/condition.js',
			'src/code/delete.js',
			'src/code/differs.js',
			'src/code/dot.js',
			'src/code/equals.js',
			'src/code/fail.js',
			'src/code/file.js',
			'src/code/for-in.js',
			'src/code/for.js',
			'src/code/func-arg.js',
			'src/code/func.js',
			'src/code/greater-than.js',
			'src/code/if.js',
			'src/code/instanceof.js',
			'src/code/less-than.js',
			'src/code/member.js',
			'src/code/new.js',
			'src/code/not.js',
			'src/code/number-literal.js',
			'src/code/obj-literal.js',
			'src/code/or.js',
			'src/code/plus.js',
			'src/code/plus-assign.js',
			'src/code/pre-increment.js',
			'src/code/return.js',
			'src/code/string-literal.js',
			'src/code/switch.js',
			'src/code/typeof.js',
			'src/code/var.js',
			'src/code/var-dec.js',
			'src/code/vlist.js',
			'src/format/context.js',
			'src/jion/gen.js'
		]
};
