/*
| All jion files to be generated for the use of the ideoloom server.
|
| Order does not matter, therefore alphabetically.
*/
module.exports =
{
	app :
		'server',
	list :
		[
			'src/change/grow.js',
			'src/change/insert.js',
			'src/change/join.js',
			'src/change/ray.js',
			'src/change/remove.js',
			'src/change/set.js',
			'src/change/shrink.js',
			'src/change/split.js',
			'src/change/wrap.js',
			'src/change/wrapRay.js',

			'src/database/changeSkid.js',
			'src/database/changeSkidRay.js',
			'src/database/userSkid.js',
			'src/database/repository.js',

			'src/euclid/margin.js',
			'src/euclid/point.js',
			'src/euclid/rect.js',
			'src/euclid/view.js',

			'src/fabric/doc.js',
			'src/fabric/label.js',
			'src/fabric/note.js',
			'src/fabric/para.js',
			'src/fabric/portal.js',
			'src/fabric/relation.js',
			'src/fabric/space.js',
			'src/fabric/spaceRef.js',

			'src/mark/caret.js',
			'src/mark/item.js',
			'src/mark/range.js',
			'src/mark/text.js',
			'src/mark/widget.js',

			'src/jion/path.js',

			'src/reply/acquire.js',
			'src/reply/alter.js',
			'src/reply/auth.js',
			'src/reply/error.js',
			'src/reply/register.js',
			'src/reply/update.js',

			'src/request/acquire.js',
			'src/request/alter.js',
			'src/request/auth.js',
			'src/request/register.js',
			'src/request/update.js',

			'src/result/genjion.js',

			'src/server/inventory.js',
			'src/server/resource.js',
			'src/server/root.js',
			'src/server/spaceBox.js',
			'src/server/spaceNexus.js',
			'src/server/upSleep.js',
			'src/server/upSleepGroup.js',
			'src/server/userNexus.js',

			'src/user/creds.js',
			'src/user/info.js',
			'src/user/infoGroup.js',

			// built-in genjion
			'src/ast/and.js',
			'src/ast/arrayLiteral.js',
			'src/ast/assign.js',
			'src/ast/block.js',
			'src/ast/boolean.js',
			'src/ast/call.js',
			'src/ast/case.js',
			'src/ast/check.js',
			'src/ast/comma.js',
			'src/ast/comment.js',
			'src/ast/condition.js',
			'src/ast/continue.js',
			'src/ast/delete.js',
			'src/ast/differs.js',
			'src/ast/dot.js',
			'src/ast/equals.js',
			'src/ast/fail.js',
			'src/ast/for.js',
			'src/ast/forIn.js',
			'src/ast/func.js',
			'src/ast/funcArg.js',
			'src/ast/greaterThan.js',
			'src/ast/if.js',
			'src/ast/instanceof.js',
			'src/ast/lessThan.js',
			'src/ast/member.js',
			'src/ast/multiply.js',
			'src/ast/multiplyAssign.js',
			'src/ast/new.js',
			'src/ast/not.js',
			'src/ast/null.js',
			'src/ast/number.js',
			'src/ast/objLiteral.js',
			'src/ast/or.js',
			'src/ast/plus.js',
			'src/ast/plusAssign.js',
			'src/ast/preIncrement.js',
			'src/ast/return.js',
			'src/ast/string.js',
			'src/ast/switch.js',
			'src/ast/typeof.js',
			'src/ast/var.js',
			'src/ast/varDec.js',

			'src/format/context.js',
			'src/jsLexer/token.js',
			'src/jsLexer/tokenRay.js',
			'src/jion/attribute.js',
			'src/jion/attributeGroup.js',
			'src/jion/concern.js',
			'src/jion/generator.js',
			'src/jion/id.js',
			'src/jion/idGroup.js',
			'src/jion/stringRay.js',
			'src/jsParser/state.js',
			'src/jsParser/spec.js',
			'src/jsParser/tokenRay.js'
		]
};
