/*
| Generates jools like objects from a jools definition.
|
| Version 2
|
| Authors: Axel Kittenberger
*/


/*
| Exports.
*/
var
	Generator =
		{ };


/*
| Imports.
*/
var
	Code;


/*
| Capsule (to make jshint happy)
*/
(function( ) {
'use strict';


/*
| Node includes.
*/
if( SERVER )
{
	Code =
		{
			File :
				require( '../code/file' )
		};
}


/*
| Generates code from a jools object definition.
*/
Generator.generate =
	function(
		//joobj // the jools object definition
	)
{
	var
		file;

	file =
		Code.File.create(
			'header',
				[
					'This is an autogenerated file.',
					'',
					'DO NOT EDIT!'
				]
		);

	return file;
};


/*
| Node export
*/
if( SERVER )
{
	module.exports =
		Generator;
}


} )( );
