/*
| Generates jools like objects from a jools definition.
|
| FIXME remove all mutable pushes
|
| Version 2
|
| Authors: Axel Kittenberger
*/


/*
| Exports.
*/
var
	Generator =
		{ };


/*
| Imports.
*/
var
	Code,
	Jools,
	Validator;


/*
| Capsule.
*/
(function( ) {
'use strict';


/*
| Node includes.
*/
if( SERVER )
{
	Code =
		{
			Block :
				require( '../code/block' ),
			Comment :
				require( '../code/comment' ),
			File :
				require( '../code/file' )
		};

	Jools =
		require( '../jools/jools' );

	Validator =
		require( './validator' );
}


/*
| Generates the constructor.
*/
var _generateConstructor =
	function(
		joobj,  // the joobj definition
		content
	)
{
	content.push(
		Code.Comment.create(
			'content',
				[ 'Constructor.' ]
		)
	);
};


/*
| Generates the capsule.
*/
var _generateCapsule =
	function(
		joobj // the joobj definition
	)
{
	var
		content =
			[ ];

	_generateConstructor( joobj, content );

	return (
		Code.Block.create(
			'content',
				content
		)
	);
};


/*
| Generates code from a jools object definition.
*/
Generator.generate =
	function(
		joobj // the joobj definition
	)
{
	var
		capsule,
		header,
		file;

	Validator.check( joobj );

	header =
		Code.Comment.create(
			'content',
				[
					'This is an autogenerated file.',
					'',
					'DO NOT EDIT!'
				]
		);

	file =
		Code.File.create(
			'header',
				header
		);

	capsule =
		_generateCapsule( joobj );


	file =
		file.create(
			'capsule',
				capsule
		);

	return file;
};


/*
| Node export
*/
if( SERVER )
{
	module.exports =
		Generator;
}


} )( );
