/*
| A user on a skid for database storage.
*/


/*
| Capsule
*/
( function( ) {
"use strict";


/*
| The jion definition.
*/
if( JION )
{
	return {
		id :
			'database_userSkid',
		attributes :
			{
				_id :
					{
						comment :
							'the username',
						json :
							true,
						type :
							'string',
					},
				passhash :
					{
						comment :
							'password hash',
						json :
							true,
						type :
							'string'
					},
				mail :
					{
						comment :
							'the users email',
						json :
							true,
						type :
							'string',
						defaultValue :
							'""'
					},
				news :
					{
						comment :
							'if the user checked okay with news emails',
						json :
							true,
						type :
							[ 'boolean', 'string' ],
					},
				clearPass :
					{
						comment :
							'clear password for autogenerated users',
						json :
							true,
						type :
							'string',
						allowsUndefined :
							true
					}
			}
	};
}


var
	database_userSkid,
	server_user,
	jools;

database_userSkid = require( '../jion/this' )( module );

server_user = require( '../server/user' );

jools = require( '../jools/jools' );


/*
| Creates a database_userSkid from a server_user.
*/
database_userSkid.createFromUser =
	function(
		user
	)
{
	// FUTURE aheadValue server_user, asUser

	return(
		database_userSkid.create(
			'_id', user.name,
			'passhash', user.passhash,
			'mail', user.mail,
			'news', user.news,
			'clearPass', user.clearPass
		)
	);
};



jools.lazyValue(
	database_userSkid.prototype,
	'asUser',
	function( )
{
	return(
		server_user.create(
			'name', this._id,
			'passhash', this.passhash,
			'mail', this.mail,
			'news', this.news,
			'clearPass', this.clearPass
		)
	);
}
);


}( ) );
